##Numpy Assignement.


###1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that you can import and use in your programs. It provides functions and classes that help you avoid writing code from scratch for common tasks, such as math operations, data manipulation, web requests, etc.

We use Python libraries because:


They save time and effort.

They ensure code reusability.

They offer tested and optimized functions.

They simplify complex tasks (e.g., data analysis, machine learning).




###2.2. What is the difference between a NumPy array and a Python list?



1. NumPy Array :
Homogeneous: All elements must be of the same type.

Supports multi-dimensional arrays.

Supports element-wise operations.

Requires less memory and is faster.

2.Python List :

Heterogeneous: Elements can be of different types.

Only supports 1D lists (nested lists can simulate 2D)

No built-in support for element-wise operations.

Requires more memory and is slower.


### 3. Find the shape, size, and dimension of the following array?

In [2]:
import numpy as np
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
shape = array.shape
size = array.size
dimension = array.ndim
shape, size, dimension

((3, 4), 12, 2)

###4.4. Write Python code to access the first row of the following array:

In [3]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = array[0]
first_row

array([1, 2, 3, 4])

###5. How do you access the element at the third row and fourth column from the given numpy array?

In [4]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
element = array[2, 3]
element

12

###6. Write code to extract all odd-indexed elements from the given numpy array:

In [5]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_indexed_elements = array[:, 1::2]
odd_indexed_elements

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

###7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.92127795, 0.88492557, 0.98882546],
       [0.50053191, 0.85292848, 0.28384178],
       [0.9079622 , 0.40558929, 0.00257562]])

###8. Difference between np.random.rand and np.random.randn

Answer :
np.random.rand(): Generates random numbers from a uniform distribution between 0 and 1.

np.random.randn(): Generates random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

###9. Write code to increase the dimension of the following array:

In [7]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
new_array = np.expand_dims(array, axis=0)  # Adding a new axis
new_array.shape

(1, 3, 4)

###10. How to transpose the following array in NumPy?


In [8]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_array = np.transpose(array)
transposed_array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

###11. Perform the following operations on matrices A and B:

In [9]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A * B

# Matrix multiplication
matrix_multiplication = np.dot(A, B.T)

# Add both matrices
matrix_addition = A + B

# Subtract matrix B from A
matrix_subtraction = A - B

# Divide Matrix B by A
matrix_division = B / A

index_wise_multiplication, matrix_multiplication, matrix_addition, matrix_subtraction, matrix_division

(array([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]),
 array([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

###12. Which function in Numpy can be used to swap the byte order of an array?

Answer : Function: np.ndarray.byteswap() can be used to swap the byte order of an array

###13. What is the significance of the np.linalg.inv function?
Function: np.linalg.inv() computes the inverse of a square matrix. The inverse is useful in solving systems of linear equations, among other applications.


###14. What does the np.reshape function do, and how is it used?
Function: np.reshape() changes the shape of an array without modifying its data. You can use it to rearrange the elements of an array into a specified shape.

In [10]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(array, (2, 3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

###15. What is broadcasting in NumPy?
Broadcasting allows NumPy to perform operations on arrays of different shapes. It automatically expands the dimensions of smaller arrays to match the larger ones without needing to create a full-size array.

In [11]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
result = a + b  # Broadcasting makes the dimensions compatible